config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask' => 'questions#ask'
  get 'answer' => 'questions#answer'
  # root to: 'questions#home'
end


# Rails.application.routes.draw do
#   get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    @question = params[:question]
    if params[:question] == "I am going to work"
      @answer = "Great !"
    elsif params[:question].include?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work"
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1> Stupid Coaching </h1>
 <p><%= @question %></p>
<%= @answer %>
<%= link_to "Ask a new question", ask_path %>

app/views/questions/ask.html.erb
<form action="/answer">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>